# Generated by Django 5.0.6 on 2024-12-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Numéro de lot', max_length=50, unique=True)),
                ('expiry_date', models.DateField(help_text='Date d’expiration')),
            ],
        ),
    ]
