# Generated by Django 5.0.6 on 2024-12-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, help_text='Code produit', max_length=50, unique=True)),
                ('brand_name', models.CharField(help_text='Designation', max_length=255)),
                ('generic_name_dosage', models.CharField(help_text='DCI et Dosage', max_length=255)),
                ('pack_size', models.CharField(help_text='Conditionnement', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit Price of the product', max_digits=10)),
                ('batch', models.ForeignKey(help_text='Batch associated with this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.batch')),
            ],
            options={
                'unique_together': {('product_code', 'batch')},
            },
        ),
    ]
