# Generated by Django 5.0.6 on 2024-12-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='generic_name_dosage',
            field=models.CharField(blank=True, help_text='DCI et Dosage', max_length=255),
        ),
    ]
