# Generated by Django 5.0.6 on 2024-12-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_batch_generic_name_dosage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='generic_name_dosage',
        ),
    ]
