# Generated by Django 5.0.6 on 2024-12-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_batch_generic_name_dosage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand_name', 'batch')},
        ),
    ]
