# Generated by Django 5.0.6 on 2024-12-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(help_text='Numéro de lot', max_length=50),
        ),
    ]
