# Generated by Django 5.0.6 on 2024-12-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_batch_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(help_text='Numéro de lot', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Code produit', max_length=50),
        ),
    ]
