# Generated by Django 5.0.6 on 2024-12-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandName', '0002_brandnamemodel'),
        ('genericName', '0001_initial'),
        ('pack_size', '0001_initial'),
        ('products', '0009_alter_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(help_text='Brand Name associated with this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brandName.brandnamemodel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name_dosage',
            field=models.ForeignKey(help_text='Generic Name associated with this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='genericName.genericname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.ForeignKey(help_text='Pack Size associated with this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pack_size.packsize'),
        ),
    ]
