# Generated by Django 5.0.6 on 2024-12-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='generic_name',
            field=models.CharField(default='null', help_text='Generic Name', max_length=255),
            preserve_default=False,
        ),
    ]
