# Generated by Django 5.0.6 on 2024-12-22 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0002_genericname_brand_name'),
        ('products', '0011_batch_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(help_text='Batch Number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(help_text='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='generic_name',
            field=models.ForeignKey(help_text='Generic Name', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='genericName.genericname'),
        ),
    ]
