# Generated by Django 5.0.6 on 2024-12-22 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0002_genericname_brand_name'),
        ('products', '0012_alter_batch_batch_number_alter_batch_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(help_text='Brand Name associated with this product', on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='genericName.genericname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name_dosage',
            field=models.ForeignKey(blank=True, help_text='Generic Name associated with this product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosage_products', to='genericName.genericname'),
        ),
    ]
