# Generated by Django 5.0.6 on 2025-01-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0002_genericname_brand_name'),
        ('pack_size', '0001_initial'),
        ('products', '0014_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.batch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='genericName.genericname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name_dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosage_products', to='genericName.genericname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pack_size.packsize'),
        ),
    ]
