# Generated by Django 5.0.6 on 2025-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_batch_batch_number_alter_batch_generic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='bl_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
