# Generated by Django 5.0.6 on 2025-01-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_batch_bl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('Injection', 'Injection'), ('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Solution', 'Solution'), ('Infusion', 'Infusion')], null=True),
        ),
    ]
