# Generated by Django 5.0.6 on 2025-01-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_dosage_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='prod_date',
            field=models.DateField(help_text='Production Date', null=True),
        ),
    ]
