# Generated by Django 5.0.6 on 2025-01-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_batchauditlog_productauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('update_price', 'Update Price'), ('delete', 'Delete')], max_length=50),
        ),
    ]
