# Generated by Django 5.0.6 on 2025-02-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_productauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='DosageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subcategory Name')),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_types', to='products.dosageform')),
            ],
            options={
                'unique_together': {('dosage_form', 'name')},
            },
        ),
    ]
