# Generated by Django 5.0.6 on 2025-02-03 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_dosageform_dosagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.dosagetype', verbose_name='Dosage Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.dosageform', verbose_name='Dosage Form'),
        ),
    ]
