# Generated by Django 5.0.6 on 2025-02-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0009_genericnameauditlog'),
        ('pack_size', '0006_alter_packsize_pack_size'),
        ('products', '0026_alter_batch_batch_number_alter_batch_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.batch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='genericName.genericname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pack_size.packsize'),
        ),
    ]
