# Generated by Django 5.0.6 on 2025-02-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0009_genericnameauditlog'),
        ('pack_size', '0006_alter_packsize_pack_size'),
        ('products', '0027_alter_product_batch_alter_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.batch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name_dosage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosage_products', to='genericName.genericname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pack_size.packsize'),
        ),
    ]
