# Generated by Django 5.0.6 on 2025-02-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0009_genericnameauditlog'),
        ('products', '0028_alter_product_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='genericName.genericname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name_dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosage_products', to='genericName.genericname'),
        ),
    ]
