# Generated by Django 5.0.6 on 2025-02-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
