# Generated by Django 5.0.6 on 2024-12-31 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchaseorder_grand_total_purchaseorder_status'),
        ('workers', '0005_privilege_worker_privileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Worker who approved the purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for rejection or other updates', null=True),
        ),
    ]
