# Generated by Django 5.0.6 on 2024-12-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_purchaseorder_approved_by_purchaseorder_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='temp_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
