# Generated by Django 5.0.6 on 2025-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_purchaseorderitem_temp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier for the purchase order', max_length=50, null=True, unique=True),
        ),
    ]
