# Generated by Django 5.0.6 on 2025-01-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_branch_type'),
        ('customers', '0011_customer_branch'),
        ('orders', '0007_temporarystock'),
        ('stock', '0003_initial'),
        ('workers', '0005_privilege_worker_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of the invoice', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid by the customer', max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount remaining to be paid', max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='Worker who created this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_created_by_orders', to='workers.worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sales_rep_orders', to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit of the product at the time of invoice', max_digits=10)),
                ('invoice_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.invoice')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date and time of the payment', null=True)),
                ('payment_number', models.CharField(help_text='Unique identifier for the payment', max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer')], help_text='Mode of payment used', max_length=50)),
                ('account_paid_to', models.CharField(help_text='Account or entity where the payment was sent', max_length=255)),
                ('invoice_total', models.DecimalField(decimal_places=2, help_text='Total amount of the invoice', max_digits=12)),
                ('invoice', models.ForeignKey(help_text='The invoice associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='orders.invoice')),
            ],
        ),
    ]
