# Generated by Django 5.0.6 on 2025-01-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_invoice_invoiceorderitem_invoicepaymenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoicePaymentHistory',
        ),
    ]
