# Generated by Django 5.0.6 on 2025-01-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_invoicepaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, help_text='Unique ID for the invoice', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.OneToOneField(blank=True, help_text='Associated purchase order', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder'),
        ),
    ]
