# Generated by Django 5.0.6 on 2025-01-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_invoice_invoice_id_invoice_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='temp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
