# Generated by Django 5.0.6 on 2025-01-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_purchaseorderitem_temp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Payment Ongoing', 'Payment Ongoing'), ('Payment Completed', 'Payment Completed')], default='Unpaid', help_text='Current payment status of the invoice', max_length=50),
        ),
    ]
