# Generated by Django 5.0.6 on 2025-01-04 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer')], help_text='Mode of payment used', max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('account_paid_to', models.CharField(help_text='Account or entity where the payment was sent', max_length=255)),
                ('invoice_total', models.DecimalField(decimal_places=2, help_text='Total amount of the invoice', max_digits=12)),
                ('invoice', models.ForeignKey(help_text='The invoice associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment', to='orders.invoice')),
            ],
        ),
    ]
