# Generated by Django 5.0.6 on 2025-01-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_invoicepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(editable=False, help_text='Unique identifier for the receipt', max_length=50, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the payment was made')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for this receipt', max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money')], help_text='Payment method used for this receipt', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the receipt', null=True)),
                ('invoice', models.ForeignKey(help_text='Invoice associated with this receipt', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.invoice')),
            ],
        ),
    ]
