# Generated by Django 5.0.6 on 2025-01-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='reason',
            field=models.TextField(blank=True, default='No Note', help_text='Reason for price change', null=True),
        ),
    ]
