# Generated by Django 5.0.6 on 2025-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_purchaseorderitem_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='reason',
            field=models.CharField(blank=True, default='No Note', help_text='Reason for price change', max_length=200, null=True),
        ),
    ]
