# Generated by Django 5.0.6 on 2025-01-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_purchaseorderitem_reason'),
        ('workers', '0009_employeeidcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='sales_rep',
            field=models.ForeignKey(limit_choices_to={'role': 'Sales Rep'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_orders', to='workers.worker'),
        ),
    ]
