# Generated by Django 5.0.6 on 2025-01-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_purchaseorder_sales_rep'),
        ('workers', '0021_alter_worker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('approve', 'Approve'), ('reject', 'Reject'), ('Cancel', 'Cancel'), ('delete', 'Delete')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_log_created', to='workers.worker')),
            ],
        ),
    ]
