# Generated by Django 5.0.6 on 2025-01-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderauditlog'),
        ('workers', '0021_alter_worker_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderAuditLog',
            new_name='PurchaseOrderAuditLog',
        ),
    ]
