# Generated by Django 5.0.6 on 2025-02-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_invoiceauditlog'),
        ('workers', '0021_alter_worker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_name', models.CharField(max_length=100, unique=True)),
                ('bank_code', models.CharField(max_length=10, unique=True)),
                ('code_agency', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('rib', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money')], help_text='Payment method used for this receipt', max_length=50),
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('payment_type', models.CharField(default='Bank Deposit', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='orders.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_created', to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('payment_type', models.CharField(default='Check', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='orders.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_created', to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='MomoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('master_sim_name', models.CharField(max_length=100)),
                ('master_sim_no', models.CharField(max_length=100)),
                ('momo_number', models.CharField(max_length=15, unique=True)),
                ('momo_name', models.CharField(max_length=100)),
                ('payment_type', models.CharField(default='Mobile Money', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_accounts', to='orders.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momo_created', to='workers.worker')),
            ],
        ),
    ]
