# Generated by Django 5.0.6 on 2025-02-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_bank_alter_receipt_payment_method_bankdeposit_check_and_more'),
        ('workers', '0021_alter_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_created', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='bank',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
