# Generated by Django 5.0.6 on 2025-02-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_bank_created_by_bank_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
