# Generated by Django 5.0.6 on 2025-02-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
        ('orders', '0023_alter_bank_account_name_alter_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_infos', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='check',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_infos', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='momoinfo',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_infos', to='branches.branch'),
        ),
    ]
