# Generated by Django 5.0.6 on 2025-02-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_bankdeposit_branch_alter_check_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_mode',
            field=models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Bank Deposit', 'Bank Deposit'), ('Check', 'Check')], help_text='Mode of payment used', max_length=50),
        ),
    ]
