# Generated by Django 5.0.6 on 2025-02-04 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_invoicepayment_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepayment',
            name='account_paid_to',
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='bank_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_payments', to='orders.bankdeposit'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='check_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_payments', to='orders.check'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='momo_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momo_payments', to='orders.momoinfo'),
        ),
    ]
