# Generated by Django 5.0.6 on 2025-02-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_invoicepayment_account_paid_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
