# Generated by Django 5.0.6 on 2025-02-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_bank_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Deposit', 'Bank Deposit'), ('Check', 'Check')], help_text='Mode of payment used', max_length=50),
        ),
    ]
