# Generated by Django 5.0.6 on 2025-02-12 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_invoicepayment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='bank_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_deposit_payments_order', to='orders.bankdeposit'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='check_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_check_payments_order', to='orders.check'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='momo_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_momo_payments_order', to='orders.momoinfo'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Deposit', 'Bank Deposit'), ('Check', 'Check')], max_length=50, null=True),
        ),
    ]
