# Generated by Django 5.0.6 on 2025-02-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_purchaseorder_bank_deposit_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(choices=[('Immediately', 'Immediately'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks')], max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='orders.purchaseorder')),
            ],
        ),
    ]
