# Generated by Django 5.0.6 on 2025-02-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_paymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='invoice_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='orders.invoicepayment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.invoice'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
