# Generated by Django 5.0.6 on 2025-02-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_receipt_invoice_payment_alter_receipt_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid for this receipt', max_digits=12),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice associated with this receipt', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.invoice'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for the receipt', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the payment was made'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money')], help_text='Payment method used for this receipt', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.CharField(editable=False, help_text='Unique identifier for the receipt', max_length=50, unique=True),
        ),
    ]
