# Generated by Django 5.0.6 on 2025-02-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_receipt_amount_paid_alter_receipt_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='when',
            field=models.CharField(choices=[('Upon Delivery', 'Upon Delivery'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks')], max_length=100),
        ),
    ]
