# Generated by Django 5.0.6 on 2025-02-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_paymentschedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='when',
            field=models.CharField(choices=[('Upon Delivery', 'Upon Delivery'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('5 Weeks', '5 Weeks'), ('6 Weeks', '6 Weeks')], max_length=100),
        ),
    ]
