# Generated by Django 5.0.6 on 2025-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_returnorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
