# Generated by Django 5.0.6 on 2025-02-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_purchaseorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
