# Generated by Django 5.0.6 on 2025-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_returnorderitem_reason_for_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='precompte',
            field=models.FloatField(choices=[(2.0, '2.00%'), (5.0, '5.00%'), (0.0, '0.00%')], null=True, verbose_name='PreCompte'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.FloatField(choices=[(2.0, '2.00%'), (2.2, '2.20%'), (5.0, '5.00%'), (5.5, '5.50%'), (0.0, '0.00%')], null=True, verbose_name='Tax (taux)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tva',
            field=models.FloatField(choices=[(19.25, '19.25%'), (0.0, '0.00%')], null=True, verbose_name='TVA'),
        ),
    ]
