# Generated by Django 5.0.6 on 2025-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_alter_purchaseorder_precompte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='precompte',
            field=models.DecimalField(choices=[(2.0, '2.0%'), (5.0, '5.0%'), (0.0, '0.0%')], decimal_places=2, max_digits=12, null=True, verbose_name='PreCompte'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.DecimalField(choices=[(2.0, '2.0%'), (2.2, '2.20%'), (5.0, '5.0%'), (5.5, '5.50%'), (0.0, '0.0%')], decimal_places=2, max_digits=12, null=True, verbose_name='Tax (taux)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tva',
            field=models.DecimalField(choices=[(19.25, '19.25%'), (0.0, '0.0%')], decimal_places=2, max_digits=12, null=True, verbose_name='TVA'),
        ),
    ]
