# Generated by Django 5.0.6 on 2025-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_alter_purchaseorder_precompte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_special_customer',
            field=models.BooleanField(default=False, null=True, verbose_name='Is a Special Customer'),
        ),
    ]
