# Generated by Django 5.0.6 on 2025-03-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_purchaseorder_is_special_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='document',
            field=models.FileField(null=True, upload_to='purchase_order_documents/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='document_type',
            field=models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Invoice', 'Invoice'), ('Receipt', 'Receipt')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
