# Generated by Django 5.0.6 on 2025-03-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_purchaseorder_document_purchaseorder_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='document',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='PurchaseOrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Invoice', 'Invoice')], max_length=50)),
                ('document', models.FileField(null=True, upload_to='purchase_order_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.purchaseorder')),
            ],
        ),
    ]
