# Generated by Django 5.0.6 on 2025-03-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_remove_purchaseorder_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='old_invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='old_purchase_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
