# Generated by Django 5.0.6 on 2025-03-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
        ('customers', '0019_customerauditlog'),
        ('orders', '0048_invoice_old_invoice_id_and_more'),
        ('stock', '0013_stock_total_sold'),
        ('workers', '0027_alter_roleprivilege_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='precompte',
            field=models.DecimalField(choices=[(2.0, '2.0%'), (5.0, '5.0%'), (0.0, '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='PreCompte'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.DecimalField(choices=[(2.0, '2.0%'), (2.2, '2.20%'), (5.0, '5.0%'), (5.5, '5.50%'), (0.0, '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tax (taux)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tva',
            field=models.DecimalField(choices=[(19.25, '19.25%'), (0.0, '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='TVA'),
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_invoice_id', models.CharField(blank=True, help_text='Unique ID for the return invoice', max_length=50, unique=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of the return invoice', max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount refunded to the customer', max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount that needs to be refunded', max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('Rejected', 'Rejected')], default='Pending', help_text='Current refund status of the return invoice', max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_created_by_orders', to='workers.worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('original_invoice', models.ForeignKey(help_text='Reference to the original invoice', on_delete=django.db.models.deletion.CASCADE, to='orders.invoice')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_invoice_sales_rep_orders', to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnInvoiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit of the product at the time of return', max_digits=10)),
                ('return_invoice_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returninvoice')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', help_text='Status of the return purchase order', max_length=50)),
                ('return_order_id', models.CharField(blank=True, editable=False, help_text='Unique identifier for the return purchase order', max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes regarding the return', null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of the return purchase order', max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_created_by_orders', to='workers.worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('original_purchase_order', models.ForeignKey(help_text='Reference to the original purchase order', on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
                ('sales_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_sales_rep_orders', to='workers.worker')),
            ],
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='return_purchase_order',
            field=models.OneToOneField(blank=True, help_text='Associated return purchase order', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.returnpurchaseorder'),
        ),
        migrations.CreateModel(
            name='ReturnPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('return_reason', models.TextField(blank=True, help_text='Reason for returning this item', null=True)),
                ('return_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnpurchaseorder')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
