# Generated by Django 5.0.6 on 2025-03-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_alter_purchaseorder_precompte_and_more'),
        ('workers', '0027_alter_roleprivilege_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returninvoiceorderitem',
            old_name='return_invoice_order',
            new_name='return_invoice',
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='old_return_invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Worker who approved the return purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_approved_orders', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='bank_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_deposit_payments_order', to='orders.bankdeposit'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='check_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_check_payments_order', to='orders.check'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='is_special_customer',
            field=models.BooleanField(default=False, null=True, verbose_name='Is a Special Customer'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='momo_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_momo_payments_order', to='orders.momoinfo'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='old_return_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Deposit', 'Bank Deposit'), ('Check', 'Check')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='precompte',
            field=models.DecimalField(choices=[(2.0, '2.0%'), (5.0, '5.0%'), (0.0, '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='PreCompte'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='tax_rate',
            field=models.DecimalField(choices=[(2.0, '2.0%'), (2.2, '2.20%'), (5.0, '5.0%'), (5.5, '5.50%'), (0.0, '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tax (taux)'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='tva',
            field=models.DecimalField(choices=[(19.25, '19.25%'), (0.0, '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='TVA'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorderitem',
            name='temp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Worker who created this return invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_created_by_orders', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorder',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Worker who created this return order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_created_by_orders', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for rejection or other updates', null=True),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorder',
            name='sales_rep',
            field=models.ForeignKey(limit_choices_to={'role': 'Sales Rep'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_sales_rep_orders', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the return purchase order', max_length=50),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorderitem',
            name='return_reason',
            field=models.CharField(blank=True, default='No Note', help_text='Reason for return', max_length=200, null=True),
        ),
    ]
