# Generated by Django 5.0.6 on 2025-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_rename_return_invoice_order_returninvoiceorderitem_return_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returninvoiceorderitem',
            old_name='price',
            new_name='temp_price',
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
