# Generated by Django 5.0.6 on 2025-03-19 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_rename_price_returninvoiceorderitem_temp_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='return_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_invoice_payments', to='orders.returninvoice'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='return_invoice',
            field=models.ForeignKey(blank=True, help_text='Return invoice associated with this receipt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_receipts', to='orders.returninvoice'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='orders.invoice'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice associated with this receipt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.invoice'),
        ),
    ]
