# Generated by Django 5.0.6 on 2025-03-19 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_invoicepayment_return_invoice_receipt_return_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepayment',
            name='return_invoice',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='return_invoice',
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(help_text='The invoice associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment', to='orders.invoice'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice associated with this receipt', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.invoice'),
        ),
    ]
