# Generated by Django 5.0.6 on 2025-03-19 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_remove_invoicepayment_return_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Deposit', 'Bank Deposit'), ('Check', 'Check')], help_text='Mode of payment used', max_length=50)),
                ('payment_date', models.DateTimeField(null=True)),
                ('invoice_total', models.DecimalField(decimal_places=2, help_text='Total amount of the invoice', max_digits=12)),
                ('bank_deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_deposit_payments', to='orders.bankdeposit')),
                ('check_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_check_payments', to='orders.check')),
                ('momo_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_momo_payments', to='orders.momoinfo')),
                ('return_invoice', models.ForeignKey(help_text='The return invoice associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='return_invoice_payment', to='orders.returninvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(editable=False, help_text='Unique identifier for the receipt', max_length=50, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the payment was made')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for this receipt', max_digits=12)),
                ('payment_method', models.CharField(choices=[('Credit', 'Credit'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money')], help_text='Payment method used for this receipt', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the receipt', null=True)),
                ('return_invoice', models.ForeignKey(help_text='Return Invoice associated with this receipt', on_delete=django.db.models.deletion.CASCADE, related_name='return_receipts', to='orders.returninvoice')),
                ('return_invoice_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_receipts', to='orders.returninvoicepayment')),
            ],
        ),
    ]
