# Generated by Django 5.0.6 on 2025-03-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_returninvoicepayment_returnreceipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returninvoice',
            old_name='amount_refunded',
            new_name='amount_paid',
        ),
    ]
