# Generated by Django 5.0.6 on 2025-03-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_rename_amount_refunded_returninvoice_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnreceipt',
            name='return_invoice_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='orders.returninvoicepayment'),
        ),
    ]
