# Generated by Django 5.0.6 on 2025-03-20 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_alter_returnreceipt_return_invoice_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPurchaseOrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Purchase Order', 'Purchase Order')], max_length=50)),
                ('document', models.FileField(null=True, upload_to='return_purchase_order_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('return_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.returnpurchaseorder')),
            ],
        ),
    ]
