# Generated by Django 5.0.6 on 2025-03-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_invoicedocument_returninvoicedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdocument',
            name='document_type',
            field=models.CharField(choices=[('Purchase Order', 'Purchase Order')], max_length=50),
        ),
    ]
