# Generated by Django 5.0.6 on 2025-03-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_alter_purchaseorderdocument_document_type'),
        ('workers', '0027_alter_roleprivilege_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Worker who uploaded document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_document', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='purchaseorderdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Worker who uploaded document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_document', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='returninvoicedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Worker who uploaded document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoice_document', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='returnpurchaseorderdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Worker who uploaded document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders_document', to='workers.worker'),
        ),
    ]
