# Generated by Django 5.0.6 on 2025-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_invoicedocument_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.DecimalField(choices=[(2.0, '2.0%'), (2.2, '2.2%'), (5.0, '5.0%'), (5.5, '5.50%'), (0.0, '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tax (taux)'),
        ),
    ]
