# Generated by Django 5.0.6 on 2025-03-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_alter_purchaseorder_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(choices=[('Upon Delivery', 'Upon Delivery'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('5 Weeks', '5 Weeks'), ('6 Weeks', '6 Weeks')], max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(null=True)),
                ('return_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_purchase_order', to='orders.purchaseorder')),
            ],
        ),
    ]
