# Generated by Django 5.0.6 on 2025-03-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_returnpaymentschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpaymentschedule',
            name='return_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_purchase_order', to='orders.returnpurchaseorder'),
        ),
    ]
