# Generated by Django 5.0.6 on 2025-03-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_alter_returnpaymentschedule_return_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_with_taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount including taxes', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount before taxes', max_digits=12),
        ),
    ]
