# Generated by Django 5.0.6 on 2025-04-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0066_returnitemtemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitemtemp',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
