# Generated by Django 5.0.6 on 2025-04-05 12:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_alter_returnitemtemp_quantity_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('2.0'), '2.0%'), (Decimal('2.20'), '2.20%'), (Decimal('5.0'), '5.0%'), (Decimal('5.50'), '5.50%'), (Decimal('0.0'), '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tax (taux)'),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorder',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('2.0'), '2.0%'), (Decimal('2.20'), '2.20%'), (Decimal('5.0'), '5.0%'), (Decimal('5.50'), '5.50%'), (Decimal('0.0'), '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tax (taux)'),
        ),
    ]
