# Generated by Django 5.0.6 on 2025-04-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_alter_purchaseorder_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdocument',
            name='document_type',
            field=models.CharField(choices=[('Picking List', 'Picking List'), ('Purchase Order', 'Purchase Order'), ('Invoice', 'Invoice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorderdocument',
            name='document_type',
            field=models.CharField(choices=[('Return Purchase Order', 'Return Purchase Order'), ('Return Invoice', 'Invoice')], max_length=50),
        ),
    ]
