# Generated by Django 5.0.6 on 2025-04-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_alter_purchaseorderdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchaseorderdocument',
            name='document_type',
            field=models.CharField(choices=[('Return Purchase Order', 'Return Purchase Order'), ('Return Invoice', 'Return Invoice')], max_length=50),
        ),
    ]
