# Generated by Django 5.0.6 on 2025-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_alter_returnpurchaseorderdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchaseorderdocument',
            name='document_type',
            field=models.CharField(choices=[('Picking List', 'Picking List'), ('Purchase Order', 'Purchase Order'), ('Invoice', 'Invoice'), ('Return Purchase Order', 'Return Purchase Order'), ('Return Invoice', 'Return Invoice')], max_length=50),
        ),
    ]
