# Generated by Django 5.0.6 on 2025-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_alter_returnpurchaseorderdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='when',
            field=models.CharField(choices=[('Upon Delivery', 'Upon Delivery'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('5 Weeks', '5 Weeks'), ('6 Weeks', '6 Weeks'), ('7 Weeks', '7 Weeks'), ('8 Weeks', '8 Weeks'), ('9 Weeks', '9 Weeks'), ('10 Weeks', '10 Weeks'), ('11 Weeks', '11 Weeks'), ('12 Weeks', '12 Weeks')], max_length=100),
        ),
        migrations.AlterField(
            model_name='returnpaymentschedule',
            name='when',
            field=models.CharField(choices=[('Upon Delivery', 'Upon Delivery'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('4 Weeks', '4 Weeks'), ('5 Weeks', '5 Weeks'), ('6 Weeks', '6 Weeks'), ('7 Weeks', '7 Weeks'), ('8 Weeks', '8 Weeks'), ('9 Weeks', '9 Weeks'), ('10 Weeks', '10 Weeks'), ('11 Weeks', '11 Weeks'), ('12 Weeks', '12 Weeks')], max_length=100),
        ),
    ]
