# Generated by Django 5.0.6 on 2025-05-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0072_alter_paymentschedule_when_and_more'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='sales_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_orders', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdocument',
            name='document_type',
            field=models.CharField(choices=[('Picking List', 'Picking List'), ('Purchase Order', 'Purchase Order'), ('Invoice', 'Invoice'), ('Receipt', 'Receipt')], max_length=50),
        ),
    ]
