# Generated by Django 5.0.6 on 2025-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0073_alter_purchaseorder_sales_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returninvoice',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='returnpurchaseorder',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
