# Generated by Django 5.0.6 on 2025-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_alter_returninvoice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateTimeField(help_text='Date and time when the payment was made', null=True),
        ),
    ]
