# Generated by Django 5.0.6 on 2025-05-09 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
        ('customers', '0019_customerauditlog'),
        ('orders', '0075_alter_receipt_payment_date'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the Sample order', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for rejection or other updates', null=True)),
                ('sample_order_id', models.CharField(blank=True, editable=False, help_text='Unique identifier for the Samplw order', max_length=50, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Worker who approved the Sample order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sample_orders', to='workers.worker')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='Worker who created this Sample Order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_sample_orders', to='workers.worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('sales_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_sample_orders', to='workers.worker')),
            ],
        ),
    ]
