# Generated by Django 5.0.6 on 2025-05-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_sampleorder'),
        ('stock', '0018_stockmovement_batch_stockmovement_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='No Note', help_text='Reason for Sample', max_length=200, null=True)),
                ('sample_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_items', to='orders.sampleorder')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
