# Generated by Django 5.0.6 on 2025-05-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0078_sampleorderauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorderitem',
            name='reason',
            field=models.CharField(blank=True, default='No Note', help_text='Reason for price change', max_length=200, null=True),
        ),
    ]
