# Generated by Django 5.0.6 on 2025-05-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
        ('orders', '0079_invoiceorderitem_reason'),
        ('stock', '0021_remove_damagedproduct_batch'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_prescription', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the Sickness order', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for rejection or other updates', null=True)),
                ('sickness_order_id', models.CharField(blank=True, editable=False, help_text='Unique identifier for the Sickness order', max_length=50, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Worker who approved the Sickness order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sickness_orders', to='workers.worker')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='Worker who created this Sickness Order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_sickness_orders', to='workers.worker')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_sickness_orders', to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='SicknessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='No Note', help_text='Reason for medication', max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit (0 if prescription, otherwise unit price)', max_digits=12, null=True)),
                ('sickness_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sickness_items', to='orders.sickness')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
