# Generated by Django 5.0.6 on 2025-05-22 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0080_sickness_sicknessitem'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='employee',
            field=models.ForeignKey(help_text='Employee for sickness orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_orders', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_sickness_order',
            field=models.BooleanField(default=False, help_text='Indicates if this is a sickness order'),
        ),
    ]
