# Generated by Django 5.0.6 on 2025-05-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_purchaseorder_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_sickness_order',
        ),
    ]
