# Generated by Django 5.0.6 on 2025-05-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0082_remove_purchaseorder_employee_and_more'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_orders', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sample', 'Sample'), ('Sickness', 'Sickness')], default='Purchase', max_length=50),
        ),
    ]
