# Generated by Django 5.0.6 on 2025-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0083_purchaseorder_employee_purchaseorder_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='has_prescription',
            field=models.BooleanField(default=False, help_text='Does this order have a prescription?', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='prescription_document',
            field=models.FileField(blank=True, help_text='Upload prescription document if available.', null=True, upload_to='prescriptions/'),
        ),
    ]
