# Generated by Django 5.0.6 on 2025-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0084_purchaseorder_has_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Sample', 'Sample'), ('Sickness', 'Sickness')], default='Purchase', max_length=50),
        ),
    ]
