# Generated by Django 5.0.6 on 2025-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0085_alter_purchaseorder_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=50, null=True),
        ),
    ]
