# Generated by Django 5.0.6 on 2025-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0086_alter_purchaseorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=50),
        ),
    ]
