# Generated by Django 5.0.6 on 2025-10-31 14:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
        ('customers', '0019_customerauditlog'),
        ('orders', '0087_alter_purchaseorder_payment_method'),
        ('stock', '0027_delete_flaggedsale'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=50)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Deposit', 'Bank Deposit'), ('Check', 'Check')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of the proforma', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the proforma', null=True)),
                ('proforma_id', models.CharField(blank=True, editable=False, help_text='Unique identifier for the proforma', max_length=50, null=True, unique=True)),
                ('is_promoted', models.BooleanField(default=False, help_text='Whether this proforma has been promoted to an order')),
                ('tax_rate', models.DecimalField(choices=[(Decimal('2.0'), '2.0%'), (Decimal('2.20'), '2.20%'), (Decimal('5.0'), '5.0%'), (Decimal('5.50'), '5.50%'), (Decimal('0.0'), '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tax (taux)')),
                ('precompte', models.DecimalField(choices=[(Decimal('2.0'), '2.0%'), (Decimal('5.0'), '5.0%'), (Decimal('0.0'), '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='PreCompte')),
                ('tva', models.DecimalField(choices=[(Decimal('19.25'), '19.25%'), (Decimal('0.0'), '0.0%')], decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='TVA')),
                ('is_special_customer', models.BooleanField(default=False, null=True, verbose_name='Is a Special Customer')),
                ('bank_deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_deposit_payments', to='orders.bankdeposit')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('check_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_check_payments', to='orders.check')),
                ('created_by', models.ForeignKey(blank=True, help_text='Worker who created this proforma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proformas', to='workers.worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('momo_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_momo_payments', to='orders.momoinfo')),
                ('promoted_to_order', models.ForeignKey(blank=True, help_text='The order this proforma was promoted to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_source', to='orders.purchaseorder')),
                ('sales_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_proformas', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('promote', 'Promote to Order'), ('delete', 'Delete'), ('edit_items', 'Edit Items')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_log_created', to='workers.worker')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('temp_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.CharField(blank=True, default='No Note', help_text='Reason for price change if applicable', max_length=200, null=True)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.proforma')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
