# Generated by Django 5.0.6 on 2026-01-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0088_proforma_proformaauditlog_proformaitem'),
        ('workers', '0030_privilegechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCustomerInvoiceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_po_number', models.CharField(blank=True, help_text='Custom PO number for special customer', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_invoice_refs_created', to='workers.worker')),
                ('invoice', models.OneToOneField(help_text='Associated invoice', on_delete=django.db.models.deletion.CASCADE, related_name='special_reference', to='orders.invoice')),
            ],
            options={
                'verbose_name': 'Special Customer Invoice Reference',
                'verbose_name_plural': 'Special Customer Invoice References',
            },
        ),
        migrations.CreateModel(
            name='SpecialCustomerItemReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_reference', models.CharField(help_text='Custom product reference/code for special customer', max_length=200)),
                ('purchase_order_item', models.ForeignKey(help_text='Reference to the purchase order item', on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorderitem')),
                ('special_invoice_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_references', to='orders.specialcustomerinvoicereference')),
            ],
            options={
                'verbose_name': 'Special Customer Item Reference',
                'verbose_name_plural': 'Special Customer Item References',
            },
        ),
    ]
