# Generated by Django 5.0.6 on 2026-01-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0089_specialcustomerinvoicereference_and_more'),
        ('workers', '0030_privilegechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeLivraisonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livraison_type', models.CharField(choices=[('full', 'Full Livraison'), ('partial', 'Partial Livraison')], default='full', max_length=20)),
                ('custom_title', models.CharField(default='BORDEREAU DE LIVRAISON', help_text='Custom title for the document', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_configs', to='orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Bon de Livraison Config',
                'verbose_name_plural': 'Bon de Livraison Configs',
            },
        ),
        migrations.CreateModel(
            name='PartialLivraisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Quantity for this partial livraison')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_items', to='orders.bondelivraisonconfig')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'Partial Livraison Item',
                'verbose_name_plural': 'Partial Livraison Items',
            },
        ),
    ]
