# Generated by Django 5.0.6 on 2024-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='Code Client', max_length=50, unique=True)),
                ('customer_name', models.CharField(help_text='Noms du client', max_length=255)),
                ('postal_code', models.CharField(blank=True, help_text='Code Postal', max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Personne de contact', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Telephone', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True)),
                ('agreement_number', models.CharField(blank=True, help_text='Numero Agreement (Authorization Number)', max_length=100, null=True)),
                ('tax_payer_number', models.CharField(blank=True, help_text='Immatriculation', max_length=100, null=True)),
                ('location_plan', models.TextField(blank=True, help_text='Localisation', null=True)),
            ],
        ),
    ]
