# Generated by Django 5.0.6 on 2024-12-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_salesagent_alter_customer_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_person',
        ),
        migrations.DeleteModel(
            name='SalesAgent',
        ),
    ]
