# Generated by Django 5.0.6 on 2024-12-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_contact_person_delete_salesagent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
