# Generated by Django 5.0.6 on 2024-12-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location_plan',
            field=models.FileField(upload_to='location_plan/'),
        ),
    ]
