# Generated by Django 5.0.6 on 2024-12-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_location_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_person',
            new_name='sales_rep',
        ),
    ]
