# Generated by Django 5.0.6 on 2024-12-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, help_text='Notes', max_length=100, null=True),
        ),
    ]
