# Generated by Django 5.0.6 on 2024-12-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_note'),
        ('workers', '0005_privilege_worker_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(blank=True, help_text='Assigned Sales Agent', limit_choices_to={'role': 'Sales Rep'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='workers.worker'),
        ),
    ]
