# Generated by Django 5.0.6 on 2025-01-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_branch_type'),
        ('customers', '0010_alter_customer_sales_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch associated with the customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='branches.branch'),
        ),
    ]
