# Generated by Django 5.0.6 on 2025-01-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_branch_type'),
        ('customers', '0011_customer_branch'),
        ('workers', '0005_privilege_worker_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Sales Rep'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_payer_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
