# Generated by Django 5.0.6 on 2025-01-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customer_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
