# Generated by Django 5.0.6 on 2025-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customer_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location_plan',
            field=models.FileField(blank=True, null=True, upload_to='location_plan/'),
        ),
    ]
