# Generated by Django 5.0.6 on 2025-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_customer_location_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
