# Generated by Django 5.0.6 on 2024-12-14 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_batch_generic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('add', 'Add Stock'), ('update', 'Update Stock'), ('reduce', 'Reduce Stock')], help_text='Type of transaction', max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity affected by the transaction')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of the transaction')),
                ('product', models.ForeignKey(help_text='Product associated with the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('product', models.OneToOneField(help_text='Product associated with the stock', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product')),
            ],
        ),
    ]
