# Generated by Django 5.0.6 on 2024-12-14 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0011_batch_generic_name'),
        ('stock', '0002_remove_stock_product_delete_inventorytransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Add Stock'), ('UPDATE', 'Update Stock'), ('REMOVE', 'Remove Stock')], help_text='Type of transaction', max_length=10)),
                ('quantity', models.IntegerField(help_text='Quantity added, updated, or removed')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the transaction')),
                ('branch', models.ForeignKey(help_text='Branch where the transaction occurred', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='branches.branch')),
                ('product', models.ForeignKey(help_text='Product involved in the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of stock at this branch')),
                ('branch', models.ForeignKey(help_text='Branch where this stock is stored', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='branches.branch')),
                ('product', models.ForeignKey(help_text='Product associated with this stock', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
