# Generated by Django 5.0.6 on 2025-01-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_address_alter_branch_branch_id_and_more'),
        ('products', '0015_alter_product_batch_alter_product_brand_name_and_more'),
        ('stock', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.product'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add Stock'), ('UPDATE', 'Update Stock'), ('REMOVE', 'Remove Stock')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
