# Generated by Django 5.0.6 on 2025-01-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_inventorytransaction_branch_and_more'),
        ('workers', '0006_alter_privilege_description_alter_privilege_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='workers.worker'),
        ),
    ]
