# Generated by Django 5.0.6 on 2025-01-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_inventorytransaction_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
