# Generated by Django 5.0.6 on 2025-01-29 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stock_date_added'),
        ('workers', '0021_alter_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_created', to='workers.worker'),
        ),
    ]
