# Generated by Django 5.0.6 on 2025-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stock_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='begining_inventory',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
