# Generated by Django 5.0.6 on 2025-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stock_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add Stock'), ('UPDATE', 'Update Stock'), ('REMOVE', 'Remove Stock')], max_length=255),
        ),
    ]
