# Generated by Django 5.0.6 on 2025-03-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_inventorytransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fixed_beginning_inventory',
            field=models.PositiveIntegerField(default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_transferred',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
