# Generated by Django 5.0.6 on 2025-03-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_stock_total_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
