# Generated by Django 5.0.6 on 2025-04-09 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
        ('products', '0031_alter_batch_batch_number'),
        ('stock', '0013_stock_total_sold'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='products.batch'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'branch', 'batch')},
        ),
    ]
