# Generated by Django 5.0.6 on 2025-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20250409_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='return_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='samples_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
