# Generated by Django 5.0.6 on 2025-05-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_stock_damaged_quantity_stock_return_quantity_and_more'),
        ('stock_request', '0038_intransit_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('REQUEST', 'Stock Request'), ('TRANSFER', 'Stock Transfer')], help_text='Whether this is a stock request or transfer.', max_length=20, verbose_name='Movement Type')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='The date the stock movement was recorded.', verbose_name='Transaction Date')),
                ('stock_request', models.ForeignKey(blank=True, help_text='The stock request associated with this movement, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_request.stockrequest', verbose_name='Stock Request')),
                ('stock_transfer', models.ForeignKey(blank=True, help_text='The stock transfer associated with this movement, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_request.stocktransfer', verbose_name='Stock Transfer')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('stock_request__isnull', False), ('stock_transfer__isnull', True)), models.Q(('stock_request__isnull', True), ('stock_transfer__isnull', False)), _connector='OR'), name='one_movement_type_only'),
        ),
    ]
