# Generated by Django 5.0.6 on 2025-05-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_batch_batch_number'),
        ('stock', '0017_stockmovement_stockmovement_one_movement_type_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The batch associated with this movement, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.batch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product associated with this stock movement.', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='The quantity of the product moved in this stock movement.', null=True, verbose_name='Quantity'),
        ),
    ]
