# Generated by Django 5.0.6 on 2025-05-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_batch_batch_number'),
        ('stock', '0018_stockmovement_batch_stockmovement_product_and_more'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of damaged products')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, help_text='Date when the damage was recorded')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the damage', null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_products', to='products.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_products_created', to='workers.worker')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Damaged Product',
                'verbose_name_plural': 'Damaged Products',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
