# Generated by Django 5.0.6 on 2025-05-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
        ('stock', '0019_damagedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedproduct',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damaged_products', to='branches.branch'),
        ),
    ]
