# Generated by Django 5.0.6 on 2025-05-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_damagedproduct_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagedproduct',
            name='batch',
        ),
    ]
