# Generated by Django 5.0.6 on 2025-05-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_remove_damagedproduct_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sickness_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
