# Generated by Django 5.0.6 on 2025-06-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_stock_sickness_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
