# Generated by Django 5.0.6 on 2025-06-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_supplier_remove_stock_supplier_name_stock_supplier'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='stock.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierStockContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity provided by this supplier')),
                ('contribution_date', models.DateTimeField(auto_now_add=True, help_text='Date when this contribution was recorded')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Add Stock'), ('UPDATE', 'Update Stock')], default='ADD', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this contribution', null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contributions', to='stock.stock')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_contributions', to='stock.supplier')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_contributions_created', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Supplier Stock Contribution',
                'verbose_name_plural': 'Supplier Stock Contributions',
                'ordering': ['-contribution_date'],
                'unique_together': {('stock', 'supplier', 'contribution_date')},
            },
        ),
    ]
