# Generated by Django 5.0.6 on 2025-10-06 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0087_alter_purchaseorder_payment_method'),
        ('stock', '0025_inventorytransaction_supplier_and_more'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, help_text='When this sale was flagged')),
                ('reason', models.TextField(blank=True, help_text='Reason for flagging this sale', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this flag has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this flag was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how this was resolved', null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_sales', to='workers.worker')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_sales', to='orders.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Worker who resolved this flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sales', to='workers.worker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_sales', to='stock.stock')),
            ],
            options={
                'verbose_name': 'Flagged Sale',
                'verbose_name_plural': 'Flagged Sales',
                'ordering': ['-flagged_at'],
                'unique_together': {('stock', 'purchase_order')},
            },
        ),
    ]
