# Generated by Django 5.0.6 on 2025-10-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_flaggedsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlaggedSale',
        ),
    ]
