# Generated by Django 5.0.6 on 2026-01-03 08:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
        ('workers', '0030_privilegechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashRefillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('channel', models.CharField(choices=[('Cash', 'Cash'), ('MTN MoMo', 'MTN MoMo'), ('Orange Money', 'Orange Money')], max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('justification', models.TextField(help_text='Reason for refill request')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_refill_approvals', to='workers.worker')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_refill_requests', to='branches.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_refill_completions', to='workers.worker')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_refill_requests', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Petty Cash Refill Request',
                'verbose_name_plural': 'Petty Cash Refill Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_cash_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Daily limit for cash disbursements', max_digits=12)),
                ('daily_momo_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Daily limit for MTN MoMo disbursements', max_digits=12)),
                ('daily_orange_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Daily limit for Orange Money disbursements', max_digits=12)),
                ('cash_refill_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Alert when cash balance falls below this amount', max_digits=12)),
                ('momo_refill_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Alert when MoMo balance falls below this amount', max_digits=12)),
                ('orange_refill_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Alert when Orange balance falls below this amount', max_digits=12)),
                ('receipt_required_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Receipts mandatory for amounts above this', max_digits=12)),
                ('requires_override_approval', models.BooleanField(default=True, help_text='Require approval for limit overrides')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_settings', to='branches.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker')),
            ],
            options={
                'verbose_name': 'Petty Cash Settings',
                'verbose_name_plural': 'Petty Cash Settings',
                'ordering': ['branch'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('Disbursement', 'Disbursement'), ('Refill', 'Refill'), ('Adjustment', 'Adjustment')], default='Disbursement', max_length=20)),
                ('channel', models.CharField(choices=[('Cash', 'Cash'), ('MTN MoMo', 'MTN MoMo'), ('Orange Money', 'Orange Money')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('Transport', 'Transport'), ('Maintenance', 'Maintenance'), ('Staff Meals', 'Staff Meals'), ('Office Supplies', 'Office Supplies'), ('Utilities', 'Utilities'), ('Communication', 'Communication'), ('Cleaning', 'Cleaning'), ('Emergency', 'Emergency'), ('Repairs', 'Repairs'), ('Fuel', 'Fuel'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(help_text='Purpose of transaction')),
                ('recipient_name', models.CharField(help_text='Person/entity receiving the cash', max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('requires_override', models.BooleanField(default=False, help_text='Exceeds daily limit')),
                ('override_approved', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_approvals', to='workers.worker')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_transactions', to='branches.branch')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_disbursements', to='workers.worker')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_requests', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Petty Cash Transaction',
                'verbose_name_plural': 'Petty Cash Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(help_text='Upload receipt image/PDF', upload_to='petty_cash_receipts/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='petty_cash.pettycashtransaction')),
            ],
            options={
                'verbose_name': 'Petty Cash Receipt',
                'verbose_name_plural': 'Petty Cash Receipts',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Create Transaction', 'Create Transaction'), ('Approve Transaction', 'Approve Transaction'), ('Reject Transaction', 'Reject Transaction'), ('Disburse Transaction', 'Disburse Transaction'), ('Cancel Transaction', 'Cancel Transaction'), ('Override Approval', 'Override Approval'), ('Create Refill Request', 'Create Refill Request'), ('Approve Refill', 'Approve Refill'), ('Complete Refill', 'Complete Refill'), ('Update Settings', 'Update Settings'), ('Upload Receipt', 'Upload Receipt'), ('Balance Adjustment', 'Balance Adjustment')], max_length=50)),
                ('details', models.TextField(help_text='Description of the action performed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_audit_logs', to='workers.worker')),
                ('refill_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='petty_cash.pettycashrefillrequest')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='petty_cash.pettycashtransaction')),
            ],
            options={
                'verbose_name': 'Petty Cash Audit Log',
                'verbose_name_plural': 'Petty Cash Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Cash', 'Cash'), ('MTN MoMo', 'MTN MoMo'), ('Orange Money', 'Orange Money')], max_length=20)),
                ('month', models.DateField(help_text='First day of the month')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_inflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_outflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_balances', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Petty Cash Balance',
                'verbose_name_plural': 'Petty Cash Balances',
                'ordering': ['-month', 'branch', 'channel'],
                'unique_together': {('branch', 'channel', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='pettycashtransaction',
            index=models.Index(fields=['branch', 'channel', 'status'], name='petty_cash__branch__84e8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='pettycashtransaction',
            index=models.Index(fields=['created_at'], name='petty_cash__created_db6abc_idx'),
        ),
        migrations.AddIndex(
            model_name='pettycashtransaction',
            index=models.Index(fields=['transaction_id'], name='petty_cash__transac_bdd32f_idx'),
        ),
        migrations.AddIndex(
            model_name='pettycashauditlog',
            index=models.Index(fields=['timestamp'], name='petty_cash__timesta_3cbbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='pettycashauditlog',
            index=models.Index(fields=['user', 'action'], name='petty_cash__user_id_916c01_idx'),
        ),
    ]
