# Generated by Django 5.0.6 on 2026-01-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashauditlog',
            name='action',
            field=models.CharField(choices=[('Create Transaction', 'Create Transaction'), ('Approve Transaction', 'Approve Transaction'), ('Reject Transaction', 'Reject Transaction'), ('Disburse Transaction', 'Disburse Transaction'), ('Cancel Transaction', 'Cancel Transaction'), ('Override Approval', 'Override Approval'), ('Create Refill Request', 'Create Refill Request'), ('Edit Refill Request', 'Edit Refill Request'), ('Delete Refill Request', 'Delete Refill Request'), ('Approve Refill', 'Approve Refill'), ('Reject Refill', 'Reject Refill'), ('Complete Refill', 'Complete Refill'), ('Update Settings', 'Update Settings'), ('Upload Receipt', 'Upload Receipt'), ('Balance Adjustment', 'Balance Adjustment')], max_length=50),
        ),
    ]
