# Generated by Django 5.0.6 on 2026-01-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0002_alter_pettycashauditlog_action'),
        ('workers', '0030_privilegechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashtransaction',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Employee receiving the cash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_receipts', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Person/entity receiving the cash (if not an employee)', max_length=200, null=True),
        ),
    ]
