# Generated by Django 5.0.6 on 2026-01-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_branch_is_active'),
        ('petty_cash', '0006_convert_category_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycashrefillrequest',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='pettycashrefillrequest',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='pettycashrefillrequest',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount disbursed as Cash', max_digits=12),
        ),
        migrations.AddField(
            model_name='pettycashrefillrequest',
            name='momo_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount disbursed as MTN MoMo', max_digits=12),
        ),
        migrations.AddField(
            model_name='pettycashrefillrequest',
            name='orange_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount disbursed as Orange Money', max_digits=12),
        ),
        migrations.AddField(
            model_name='pettycashrefillrequest',
            name='source_branch',
            field=models.ForeignKey(blank=True, help_text='Source branch for transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_refills', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='pettycashrefillrequest',
            name='source_type',
            field=models.CharField(choices=[('Central Finance', 'Central Finance'), ('Branch Transfer', 'Branch Transfer')], default='Central Finance', help_text='Where funds will come from', max_length=20),
        ),
        migrations.AlterField(
            model_name='pettycashrefillrequest',
            name='branch',
            field=models.ForeignKey(help_text='Branch requesting refill', on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_refill_requests', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='pettycashrefillrequest',
            name='justification',
            field=models.TextField(help_text='Reason for requesting refill'),
        ),
        migrations.AlterField(
            model_name='pettycashrefillrequest',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount requested', max_digits=12),
        ),
    ]
