# Generated by Django 5.0.6 on 2024-12-12 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(help_text='Sales Agent Identifier', max_length=50, unique=True)),
                ('agent_name', models.CharField(help_text='Sales Agent Name', max_length=255)),
                ('telephone', models.CharField(blank=True, help_text='Telephone', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch the Sales Agent belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_agents', to='branches.branch')),
            ],
        ),
    ]
