# Generated by Django 5.0.6 on 2024-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesagent',
            name='agent_name',
        ),
        migrations.AddField(
            model_name='salesagent',
            name='agent_firstName',
            field=models.CharField(default='unknown', help_text='Sales Agent First Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesagent',
            name='agent_lastName',
            field=models.CharField(default='unknown', help_text='Sales Agent Last Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesagent',
            name='agent_manager',
            field=models.CharField(default='unkown', help_text='Sales Agent Manager', max_length=255),
            preserve_default=False,
        ),
    ]
