# Generated by Django 5.0.6 on 2024-12-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0002_remove_stockrequest_quantity_stockrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
