# Generated by Django 5.0.6 on 2024-12-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_batch_generic_name'),
        ('stock_request', '0003_stockrequest_quantity_alter_stockrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='quantity',
        ),
        migrations.CreateModel(
            name='StockRequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stock_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_request.stockrequest')),
            ],
        ),
    ]
