# Generated by Django 5.0.6 on 2024-12-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0005_intransit'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransit',
            name='stock_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_transit', to='stock_request.stockrequest'),
        ),
    ]
