# Generated by Django 5.0.6 on 2024-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0006_intransit_stock_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intransit',
            name='stock_request',
        ),
        migrations.AddField(
            model_name='intransit',
            name='status',
            field=models.CharField(default='In Transit', max_length=50),
        ),
    ]
