# Generated by Django 5.0.6 on 2024-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0008_intransit_stock_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='picking_list',
            field=models.FileField(blank=True, null=True, upload_to='picking_lists/'),
        ),
    ]
