# Generated by Django 5.0.6 on 2024-12-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0009_stockrequest_picking_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='request_number',
            field=models.CharField(default='R1002525', editable=False, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
