# Generated by Django 5.0.6 on 2025-01-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0010_stockrequest_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='request_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
