# Generated by Django 5.0.6 on 2025-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0011_alter_stockrequest_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intransit',
            name='status',
            field=models.CharField(choices=[('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='In Transit', max_length=50),
        ),
    ]
