# Generated by Django 5.0.6 on 2025-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0013_stockrequestauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequestauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('approve', 'Approve'), ('reject', 'Reject'), ('update', 'Update'), ('delete', 'Delete')], max_length=10),
        ),
    ]
