# Generated by Django 5.0.6 on 2025-02-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0014_alter_stockrequestauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransit',
            name='actual_quantity_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
