# Generated by Django 5.0.6 on 2025-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0015_intransit_actual_quantity_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransit',
            name='is_acknowledged',
            field=models.BooleanField(default=False, verbose_name='Acknowledge'),
        ),
    ]
