# Generated by Django 5.0.6 on 2025-02-11 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0018_remove_intransit_acknowleged_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='acknowleged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_stock_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_stock_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
