# Generated by Django 5.0.6 on 2025-02-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0019_stockrequest_acknowleged_by_and_more'),
        ('workers', '0023_worker_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='acknowleged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_stock_requests', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_stock_requests', to='workers.worker'),
        ),
    ]
