# Generated by Django 5.0.6 on 2025-02-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0020_alter_stockrequest_acknowleged_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrequest',
            name='acknowleged_by',
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='is_acknowledged',
        ),
    ]
