# Generated by Django 5.0.6 on 2025-02-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0021_remove_stockrequest_acknowleged_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransit',
            name='deficit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intransit',
            name='surplus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
