# Generated by Django 5.0.6 on 2025-02-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0022_intransit_deficit_intransit_surplus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='request_type',
            field=models.CharField(choices=[('Surplus', 'Surplus'), ('Deficit', 'Deficit'), ('Normal', 'Normal')], default='Normal', max_length=10),
        ),
    ]
