# Generated by Django 5.0.6 on 2025-02-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0023_stockrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequestauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('approve', 'Approve'), ('reject', 'Reject'), ('update', 'Update'), ('delete', 'Delete'), ('surplus', 'Surplus'), ('deficit', 'Deficit')], max_length=10),
        ),
    ]
