# Generated by Django 5.0.6 on 2025-03-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0024_alter_stockrequestauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequestauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Stock Request Created'), ('approve', 'Stock Request Approved'), ('reject', 'Stock Request Rejected'), ('update', 'Update'), ('delete', 'Delete'), ('surplus', 'Surplus'), ('deficit', 'Deficit')], max_length=255),
        ),
    ]
