# Generated by Django 5.0.6 on 2025-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0025_alter_stockrequestauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='requested_at',
            field=models.DateTimeField(null=True),
        ),
    ]
