# Generated by Django 5.0.6 on 2025-03-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0026_alter_stockrequest_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransit',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intransit',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
