# Generated by Django 5.0.6 on 2025-03-20 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0027_intransit_date_received_alter_intransit_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Picking List', 'Picking List'), ('Transfer Slip', 'Transfer Slip'), ('Goods Receipt Note', 'Goods Receipt Note')], max_length=50)),
                ('document', models.FileField(null=True, upload_to='stock_request_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stock_request.stockrequest')),
            ],
        ),
    ]
