# Generated by Django 5.0.6 on 2025-03-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0028_stockrequestdocument'),
        ('workers', '0027_alter_roleprivilege_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequestdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Worker who uploaded document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_request_document', to='workers.worker'),
        ),
    ]
