# Generated by Django 5.0.6 on 2025-04-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_batch_batch_number'),
        ('stock_request', '0029_stockrequestdocument_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequestproduct',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_products', to='products.batch'),
        ),
    ]
