# Generated by Django 5.0.6 on 2025-04-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0030_stockrequestproduct_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrequestproduct',
            name='batch',
        ),
    ]
