# Generated by Django 5.0.6 on 2025-04-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_batch_batch_number'),
        ('stock_request', '0031_remove_stockrequestproduct_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequestproduct',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.batch'),
        ),
        migrations.AlterField(
            model_name='stockrequestproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
