# Generated by Django 5.0.6 on 2025-04-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0033_stocktransfer_stocktransferitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
