# Generated by Django 5.0.6 on 2025-04-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0034_alter_stocktransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Surplus', 'Surplus'), ('Deficit', 'Deficit')], default='Regular', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='actual_quantity_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='deficit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='surplus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
