# Generated by Django 5.0.6 on 2025-04-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0035_stocktransfer_transfer_type_and_more'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transfer ID')),
                ('source_branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Branch')),
                ('destination_branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination Branch')),
                ('action', models.CharField(choices=[('create', 'Stock Transfer Created'), ('complete', 'Stock Transfer Completed'), ('cancel', 'Stock Transfer Cancelled'), ('update', 'Update'), ('delete', 'Delete'), ('surplus', 'Surplus Recorded'), ('deficit', 'Deficit Recorded')], max_length=255, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_log_created', to='workers.worker', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stock Transfer Audit Log',
                'verbose_name_plural': 'Stock Transfer Audit Logs',
            },
        ),
    ]
