# Generated by Django 5.0.6 on 2025-04-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0036_stocktransferauditlog'),
        ('workers', '0029_alter_privilege_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Picking List', 'Picking List'), ('Transfer Slip', 'Transfer Slip'), ('Goods Receipt Note', 'Goods Receipt Note')], max_length=50)),
                ('document', models.FileField(null=True, upload_to='stock_transfer_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stock_request.stocktransfer')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Worker who uploaded document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_document', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Stock Transfer Document',
                'verbose_name_plural': 'Stock Transfer Documents',
            },
        ),
    ]
