# Generated by Django 5.0.6 on 2025-04-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_batch_batch_number'),
        ('stock_request', '0037_stocktransferdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransit',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.batch'),
        ),
    ]
