# Generated by Django 5.0.6 on 2025-02-18 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_clearance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearanceprocess',
            old_name='timestamp',
            new_name='completed_at',
        ),
        migrations.AlterUniqueTogether(
            name='clearanceprocess',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='clearancestep',
            name='required_document',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clearancestep',
            name='step_number',
            field=models.FloatField(unique=True),
        ),
        migrations.CreateModel(
            name='ClearanceProcessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clearanceprocess',
            name='process_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='custom_clearance.clearanceprocessgroup'),
        ),
    ]
