# Generated by Django 5.0.6 on 2025-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_clearance', '0003_customlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceprocessgroup',
            name='bol_document',
            field=models.FileField(null=True, upload_to='clearance_documents/'),
        ),
        migrations.AddField(
            model_name='clearanceprocessgroup',
            name='bol_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
