# Generated by Django 5.0.6 on 2026-02-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientdocument',
            new_name='documents_c_custome_374d36_idx',
            old_name='documents_c_custome_a49e7a_idx',
        ),
        migrations.RenameIndex(
            model_name='clientdocument',
            new_name='documents_c_status_f848ba_idx',
            old_name='documents_c_status_7c0ab0_idx',
        ),
        migrations.RenameIndex(
            model_name='documentaccesslog',
            new_name='documents_d_documen_4ef1cc_idx',
            old_name='documents_d_documen_7f1c5a_idx',
        ),
        migrations.RenameIndex(
            model_name='documentaccesslog',
            new_name='documents_d_user_id_1e66a9_idx',
            old_name='documents_d_user_id_1e8b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='documentfollowup',
            new_name='documents_d_status_bac041_idx',
            old_name='documents_d_status_2a5c8e_idx',
        ),
        migrations.RenameIndex(
            model_name='documentfollowup',
            new_name='documents_d_assigne_a31c75_idx',
            old_name='documents_d_assigne_9b4e2d_idx',
        ),
    ]
