# Generated by Django 5.0.6 on 2024-12-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericname',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Brand Name (optional)', max_length=255, null=True),
        ),
    ]
