# Generated by Django 5.0.6 on 2025-01-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0002_genericname_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericname',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='genericname',
            name='generic_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
