# Generated by Django 5.0.6 on 2025-01-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0003_alter_genericname_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericname',
            name='brand_name',
        ),
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('generic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_names', to='genericName.genericname')),
            ],
        ),
    ]
