# Generated by Django 5.0.6 on 2025-01-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0004_remove_genericname_brand_name_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericname',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BrandName',
        ),
    ]
