# Generated by Django 5.0.6 on 2025-01-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0005_genericname_brand_name_delete_brandname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericname',
            name='generic_name',
            field=models.CharField(max_length=255),
        ),
    ]
