# Generated by Django 5.0.6 on 2025-01-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0006_alter_genericname_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericname',
            name='generic_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
