# Generated by Django 5.0.6 on 2025-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0009_genericnameauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericname',
            name='old_brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
