# Generated by Django 5.0.6 on 2025-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericName', '0010_genericname_old_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericname',
            name='generic_name',
            field=models.CharField(max_length=255),
        ),
    ]
