# Generated by Django 5.0.6 on 2024-12-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product'),
        ('workers', '0002_alter_worker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Recommended quantity for the next shipment.')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the recommendation.', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Current status of the recommendation.', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time the recommendation was created.')),
                ('pharmacist', models.ForeignKey(help_text='The pharmacist making the recommendation. Must be assigned the Pharmacist role.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='workers.worker')),
                ('product', models.ForeignKey(help_text='The product being recommended.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-date_created'],
            },
        ),
    ]
