# Generated by Django 5.0.6 on 2024-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_recommendation_recommendation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='product',
            field=models.CharField(help_text='Product', max_length=255),
        ),
    ]
