# Generated by Django 5.0.6 on 2024-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_recommendation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.TextField(help_text='Optional reason for the recommendation.'),
        ),
    ]
