# Generated by Django 5.0.6 on 2024-12-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_recommendation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_document',
            field=models.FileField(help_text='Upload a recommendation document (required).', upload_to='recommendation_document/'),
        ),
    ]
