# Generated by Django 5.0.6 on 2025-01-06 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_recommendation_recommendation_document'),
        ('workers', '0005_privilege_worker_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='pharmacist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='workers.worker'),
        ),
    ]
