# Generated by Django 5.0.6 on 2025-01-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_alter_recommendation_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_document',
            field=models.FileField(upload_to='recommendation_document/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
