# Generated by Django 5.0.6 on 2025-01-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_alter_recommendation_date_created_and_more'),
        ('workers', '0019_alter_worker_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommend_created', to='workers.worker'),
        ),
    ]
