# Generated by Django 5.0.6 on 2024-12-13 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Director', 'Director'), ('Pharmacist', 'Pharmacist'), ('Marketing Director', 'Marketing Director'), ('Stock Manager', 'Stock Manager'), ('Stock Keeper', 'Stock Keeper'), ('Accountant', 'Accountant'), ('Cashier', 'Cashier'), ('Secretary', 'Secretary'), ('Accountant', 'Accountant'), ('Driver', 'Driver'), ('Other', 'Other')], default='Other', help_text='Role of the worker in the organization', max_length=50)),
                ('employee_id', models.CharField(help_text='Unique identifier for the worker', max_length=50, unique=True)),
                ('telephone', models.CharField(blank=True, help_text='Telephone number of the worker', max_length=20, null=True)),
                ('department', models.TextField(blank=True, help_text='Department of the worker', null=True)),
                ('address', models.TextField(blank=True, help_text='Address of the worker', null=True)),
                ('date_joined', models.DateField(auto_now_add=True, help_text='Date when the worker joined')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch the worker belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='branches.branch')),
                ('user', models.OneToOneField(help_text='Associated user account for the worker', on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'ordering': ['branch', 'role'],
            },
        ),
    ]
