# Generated by Django 5.0.6 on 2024-12-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('Director', 'Director'), ('Pharmacist', 'Pharmacist'), ('Marketing Director', 'Marketing Director'), ('Stock Manager', 'Stock Manager'), ('Stock Keeper', 'Stock Keeper'), ('Accountant', 'Accountant'), ('Cashier', 'Cashier'), ('Secretary', 'Secretary'), ('Driver', 'Driver'), ('Other', 'Other')], default='Other', help_text='Role of the worker in the organization', max_length=50),
        ),
    ]
