# Generated by Django 5.0.6 on 2024-12-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_worker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the privilege', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the privilege', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='privileges',
            field=models.ManyToManyField(blank=True, help_text='Privileges assigned to the worker', related_name='workers', to='workers.privilege'),
        ),
    ]
