# Generated by Django 5.0.6 on 2025-01-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_privilege_worker_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
