# Generated by Django 5.0.6 on 2025-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_alter_privilege_description_alter_privilege_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('Director', 'Director'), ('Pharmacist', 'Pharmacist'), ('Human Resource', 'Human Resource'), ('Marketing Director', 'Marketing Director'), ('Central Stock Manager', 'Central Stock Manager'), ('Stock Manager', 'Stock Manager'), ('Central Stock Keeper', 'Central Stock Keeper'), ('Stock Keeper', 'Stock Keeper'), ('Accountant', 'Accountant'), ('Cashier', 'Cashier'), ('Secretary', 'Secretary'), ('Sales Rep', 'Sales Rep'), ('Driver', 'Driver'), ('Other', 'Other')], default='Other', help_text='Role of the worker in the organization', max_length=50),
        ),
    ]
