# Generated by Django 5.0.6 on 2025-01-21 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branch_branch_name'),
        ('workers', '0007_alter_worker_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='privileges',
            field=models.ManyToManyField(blank=True, related_name='workers', to='workers.privilege'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('Director', 'Director'), ('Pharmacist', 'Pharmacist'), ('Human Resource', 'Human Resource'), ('Marketing Director', 'Marketing Director'), ('Central Stock Manager', 'Central Stock Manager'), ('Stock Manager', 'Stock Manager'), ('Central Stock Keeper', 'Central Stock Keeper'), ('Stock Keeper', 'Stock Keeper'), ('Accountant', 'Accountant'), ('Cashier', 'Cashier'), ('Secretary', 'Secretary'), ('Sales Rep', 'Sales Rep'), ('Driver', 'Driver'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
