# Generated by Django 5.0.6 on 2025-01-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_alter_worker_address_alter_worker_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
