# Generated by Django 5.0.6 on 2025-01-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_employeeidcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='contract_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='marital_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='recruitment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
