# Generated by Django 5.0.6 on 2025-01-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_worker_company_worker_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Widower', 'Widower')], max_length=20, null=True),
        ),
    ]
