# Generated by Django 5.0.6 on 2025-01-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_alter_worker_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='company',
            field=models.CharField(blank=True, choices=[('GC Pharma', 'GC Pharma'), ('2A Promo', '2A Promo')], null=True),
        ),
    ]
