# Generated by Django 5.0.6 on 2025-01-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_alter_worker_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, choices=[('SR', 'Commercial | Sales & Marketing'), ('FIN', 'Finance'), ('PH', 'Pharmacie | Pharmacy'), ('HR', 'Ressoure Humaine | Human Resource')], null=True),
        ),
    ]
