# Generated by Django 5.0.6 on 2025-01-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_alter_worker_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the worker can log in.', verbose_name='Active'),
        ),
    ]
