# Generated by Django 5.0.6 on 2025-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_worker_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Contrat à Durée Indéterminée (CDI)/Permanent Contract', 'Contrat à Durée Indéterminée (CDI)/Permanent Contract'), ('Contrat à durée déterminée ( CDD) /Fixed-term Contract', 'Contrat à durée déterminée ( CDD) /Fixed-term Contract'), ('Contrat d’essai / Trial contract', 'Contrat d’essai / Trial contract')], null=True),
        ),
    ]
