# Generated by Django 5.0.6 on 2025-01-24 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branch_branch_name'),
        ('workers', '0015_alter_worker_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='branches.branch'),
        ),
    ]
