# Generated by Django 5.0.6 on 2025-01-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_alter_worker_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='company',
            field=models.CharField(blank=True, choices=[('GC Pharma', 'GC Pharma'), ('2A Promo', '2A-Promo')], null=True),
        ),
    ]
