# Generated by Django 5.0.6 on 2025-01-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_alter_worker_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_created', to='workers.worker'),
        ),
    ]
