# Generated by Django 5.0.6 on 2025-02-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0021_alter_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Indicates whether the worker is currently online.', verbose_name='Online Status'),
        ),
    ]
