# Generated by Django 5.0.6 on 2025-02-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0022_worker_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
