# Generated by Django 5.0.6 on 2025-02-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0024_worker_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='security_pin',
            field=models.CharField(blank=True, help_text='A 4-digit security PIN for extra security.', max_length=128, null=True),
        ),
    ]
