# Generated by Django 5.0.6 on 2025-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0026_roleprivilege'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roleprivilege',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roleprivilege',
            name='privileges',
            field=models.ManyToManyField(related_name='role_privileges', to='workers.privilege'),
        ),
        migrations.AlterField(
            model_name='roleprivilege',
            name='role',
            field=models.CharField(choices=[('Director General', 'Director General'), ('Pharmacist', 'Pharmacist'), ('Human Resource', 'Human Resource'), ('Marketing Director', 'Marketing Director'), ('Central Stock Manager', 'Central Stock Manager'), ('Stock Manager', 'Stock Manager'), ('Central Stock Keeper', 'Central Stock Keeper'), ('Stock Keeper', 'Stock Keeper'), ('Accountant', 'Accountant'), ('Cashier', 'Cashier'), ('Secretary', 'Secretary'), ('Sales Rep', 'Sales Rep'), ('Driver', 'Driver'), ('Other', 'Other')], max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='roleprivilege',
            name='privilege',
        ),
    ]
