# Generated by Django 5.0.6 on 2025-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0027_alter_roleprivilege_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='category',
            field=models.TextField(blank=True, choices=[('Inventory Management', 'Inventory Management'), ('Order and Sales', 'Order and sales'), ('Accounting', 'Accounting')], null=True),
        ),
    ]
