# Generated by Django 5.0.6 on 2025-04-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0028_privilege_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='category',
            field=models.TextField(blank=True, choices=[('Inventory Management', 'Inventory Management'), ('Human Resource', 'Human Resource'), ('Order and Sales', 'Order and sales'), ('Finance', 'Finance')], null=True),
        ),
    ]
