# Generated by Django 5.0.6 on 2025-12-22 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0029_alter_privilege_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10, verbose_name='Change Type')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this change', null=True, verbose_name='Notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privilege_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='workers.privilege', verbose_name='Privilege')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_changes', to='workers.worker', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Privilege Change Log',
                'verbose_name_plural': 'Privilege Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['worker', '-changed_at'], name='workers_pri_worker__aa534b_idx'), models.Index(fields=['changed_by', '-changed_at'], name='workers_pri_changed_125178_idx')],
            },
        ),
    ]
