# Generated by Django 5.0.6 on 2025-01-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_size', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsize',
            name='pack_size',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
