# Generated by Django 5.0.6 on 2025-01-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_size', '0002_alter_packsize_pack_size'),
        ('workers', '0019_alter_worker_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='packsize',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packsize_created', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='packsize',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
