# Generated by Django 5.0.6 on 2025-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_size', '0004_packsizeauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsize',
            name='pack_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
