# Generated by Django 5.0.6 on 2025-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_size', '0005_alter_packsize_pack_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsize',
            name='pack_size',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
