# Generated by Django 5.0.6 on 2026-02-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0030_privilegechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the saved report', max_length=200)),
                ('report_type', models.CharField(choices=[('client_financial', 'Client Financial'), ('regional_performance', 'Regional Performance'), ('sales_agent_performance', 'Sales Agent Performance'), ('inventory', 'Inventory & Products'), ('financial_summary', 'Financial Summary'), ('debt_analysis', 'Debt Analysis'), ('payment_analysis', 'Payment Analysis')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Make this report visible to other users')),
                ('shared_with_roles', models.JSONField(blank=True, default=list, help_text='List of roles that can access this report')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='report_exports/')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('filters_applied', models.JSONField(default=dict)),
                ('record_count', models.IntegerField(default=0)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.savedreport')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('filters_used', models.JSONField(default=dict)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.savedreport')),
            ],
            options={
                'verbose_name': 'Report Access Log',
                'verbose_name_plural': 'Report Access Logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
