# Generated by Django 5.0.6 on 2024-12-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(help_text='Branch Identifier', max_length=50, unique=True)),
                ('branch_name', models.CharField(help_text='Branch Name', max_length=255)),
                ('address', models.TextField(help_text='Branch Address')),
            ],
        ),
    ]
