# Generated by Django 5.0.6 on 2024-12-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('central', 'Central Warehouse'), ('regular', 'Regular Branch')], default='regular', help_text='Type of branch (Central or Regular)', max_length=10),
        ),
    ]
