# Generated by Django 5.0.6 on 2025-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_branch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('central', 'Central Warehouse'), ('regular', 'Regular Branch')], default='regular', max_length=10),
        ),
    ]
