# Generated by Django 5.0.6 on 2025-01-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_address_alter_branch_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=255),
        ),
    ]
