# Generated by Django 5.0.6 on 2025-01-26 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branch_branch_name'),
        ('workers', '0019_alter_worker_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_created', to='workers.worker'),
        ),
    ]
