# Generated by Django 5.0.6 on 2025-01-27 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_branchauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchauditlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
