# Generated by Django 5.0.6 on 2025-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_alter_branchauditlog_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchauditlog',
            name='branch',
        ),
        migrations.AddField(
            model_name='branchauditlog',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
