# Generated by Django 5.0.6 on 2026-01-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_remove_branchauditlog_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this branch is active for use'),
        ),
    ]
