# Generated by Django 5.0.6 on 2024-12-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_branch_type'),
        ('customers', '0010_alter_customer_sales_rep'),
        ('stock', '0003_initial'),
        ('workers', '0005_privilege_worker_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldInvoiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the purchase order', max_length=50)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of the purchase order', max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='Worker who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_invoice_created_by_orders', to='workers.worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_invoice_sales_rep_orders', to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='OldInvoiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='oldinvoice.oldinvoiceorder')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
