# Generated by Django 5.0.6 on 2024-12-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldinvoiceorder',
            name='status',
        ),
        migrations.AddField(
            model_name='oldinvoiceorder',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount remaining to be paid', max_digits=12),
        ),
        migrations.AddField(
            model_name='oldinvoiceorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid by the customer', max_digits=12),
        ),
    ]
