# Generated by Django 5.0.6 on 2024-12-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0002_remove_oldinvoiceorder_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldinvoiceorderitem',
            old_name='purchase_order',
            new_name='invoice_order',
        ),
    ]
