# Generated by Django 5.0.6 on 2024-12-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0003_rename_purchase_order_oldinvoiceorderitem_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldinvoiceorder',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Date when the invoice was created', null=True),
        ),
    ]
