# Generated by Django 5.0.6 on 2024-12-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0004_alter_oldinvoiceorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldinvoiceorder',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date by which the payment is expected', null=True),
        ),
    ]
