# Generated by Django 5.0.6 on 2024-12-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0005_oldinvoiceorder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldinvoiceorder',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Date by which the payment is expected', null=True),
        ),
    ]
