# Generated by Django 5.0.6 on 2024-12-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0006_alter_oldinvoiceorder_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldinvoiceorder',
            name='due_date',
        ),
    ]
