# Generated by Django 5.0.6 on 2024-12-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0008_invoicepaymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of the payment', null=True),
        ),
    ]
