# Generated by Django 5.0.6 on 2024-12-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0009_alter_invoicepaymenthistory_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='payment_number',
            field=models.CharField(help_text='Unique identifier for the payment', max_length=100),
        ),
    ]
