# Generated by Django 5.0.6 on 2024-12-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0010_alter_invoicepaymenthistory_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldinvoiceorderitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
