# Generated by Django 5.0.6 on 2024-12-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0011_oldinvoiceorderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldinvoiceorderitem',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
