# Generated by Django 5.0.6 on 2024-12-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0012_alter_oldinvoiceorderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldinvoiceorderitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
