# Generated by Django 5.0.6 on 2025-01-28 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0013_alter_oldinvoiceorderitem_price'),
        ('workers', '0021_alter_worker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldInvoiceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('payment', 'Payment Made')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_invoice_log_created', to='workers.worker')),
            ],
        ),
    ]
