# Generated by Django 5.0.6 on 2025-02-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('oldinvoice', '0015_remove_invoicepaymenthistory_payment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepaymenthistory',
            name='account_paid_to',
        ),
        migrations.AddField(
            model_name='invoicepaymenthistory',
            name='account_paid_to_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepaymenthistory',
            name='account_paid_to_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='oldinvoice.oldinvoiceorder'),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='payment_mode',
            field=models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer'), ('Check', 'Check')], max_length=50),
        ),
    ]
