# Generated by Django 5.0.6 on 2025-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0018_remove_invoicepaymenthistory_account_paid_to_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepaymenthistory',
            name='account_paid_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
