# Generated by Django 5.0.6 on 2025-02-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0019_invoicepaymenthistory_account_paid_to'),
        ('orders', '0026_remove_invoicepayment_account_paid_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepaymenthistory',
            name='account_paid_to',
        ),
        migrations.AddField(
            model_name='invoicepaymenthistory',
            name='bank_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_deposit_payments', to='orders.bankdeposit'),
        ),
        migrations.AddField(
            model_name='invoicepaymenthistory',
            name='check_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_check_payments', to='orders.check'),
        ),
        migrations.AddField(
            model_name='invoicepaymenthistory',
            name='momo_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_momo_payments', to='orders.momoinfo'),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='invoice',
            field=models.ForeignKey(help_text='The old invoice associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='old_invoice_payment', to='oldinvoice.oldinvoiceorder'),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, help_text='Total amount of the invoice', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='payment_mode',
            field=models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Bank Deposit', 'Bank Deposit'), ('Check', 'Check')], help_text='Mode of payment used', max_length=50),
        ),
    ]
