# Generated by Django 5.0.6 on 2025-02-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0020_remove_invoicepaymenthistory_account_paid_to_and_more'),
        ('products', '0030_alter_product_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldinvoiceorderitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='oldinvoiceorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
