# Generated by Django 5.0.6 on 2025-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0021_remove_oldinvoiceorderitem_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepaymenthistory',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Deposit', 'Bank Deposit'), ('Check', 'Check')], help_text='Mode of payment used', max_length=50),
        ),
    ]
