# Generated by Django 5.0.6 on 2025-02-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinvoice', '0023_oldinvoiceorder_old_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldinvoiceorder',
            name='old_invoice_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
